modid="sandscript-cpy" # required `[a-z0-9-_]{4,15}`
version="0.0.0" # required Semver Enforced!
title="SandScript - CPython" # optional DEFAULT: modid
description="""
Native python support for SandScript.
"""  # optional DEFAULT: ""
entrypoint="jsr223.cpython.SandScriptCPy" # required
authors = [ # required 1
    "B0undarybreaker",
]
url = "" # optional DEFAULT: ""
side = "COMMON" # optional [SERVER, CLIENT, COMMON] DEFAULT: "COMMON"
